# -*- coding: utf-8 -*-
"""KNN_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_uOfAXuM-KPT8i8aSZgg9kq8WaRIsl5
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

import_dataset_iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(
    import_dataset_iris.data,
    import_dataset_iris.target,
    test_size=0.15,
    train_size=0.70,
    shuffle=True,
    stratify=import_dataset_iris.target,
    random_state=0,
)

X_train, X_val, y_train, y_val = train_test_split(
    import_dataset_iris.data,
    import_dataset_iris.target,
    test_size=0.15,
    train_size=0.70,
    shuffle=True,
    stratify=import_dataset_iris.target,
    random_state=0,
)

KNN_Classification = KNeighborsClassifier()
KNN_Classification.fit(X_train, y_train)

KNN_Regression = KNeighborsRegressor()
KNN_Regression.fit(X_train, y_train)

print("KNN_Classification")
print("Accuracy of Train_set", KNN_Classification.score(X_train, y_train))
print("Accuracy of Test_set", KNN_Classification.score(X_test, y_test))
print("Accuracy of Val_set", KNN_Classification.score(X_val, y_val))

print("KNN_Regression")
print("Accuracy of Train_set", KNN_Regression.score(X_train, y_train))
print("Accuracy of Test_set", KNN_Regression.score(X_test, y_test))
print("Accuracy of Val_set", KNN_Regression.score(X_val, y_val))